# Numpy and Pandas

##### Importing Libraries 

In [2]:
import numpy as np
import pandas as pd

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a.ndim

1

In [6]:
a.shape

(5,)

In [7]:
b=np.array([[1,2,3],[4,5,6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.ndim

2

#### Matrix of 3*3

In [10]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [14]:
c.ndim

3

In [12]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
d.ndim

2

In [16]:
d.shape

(3, 3)

In [17]:
c.shape

(3, 3, 3)

In [18]:
b.shape

(2, 3)

In [19]:
type(d)

numpy.ndarray

In [20]:
a

array([1, 2, 3, 4, 5])

In [21]:
a=np.array([1,2,3,4,5],dtype=float)

In [22]:
a

array([1., 2., 3., 4., 5.])

In [23]:
print(a.size)

5


In [24]:
a.size

5

In [25]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
b.shape

(2, 3)

In [27]:
b.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b[1,1]

5

In [30]:
b[0:2,2]

array([3, 6])

### Linspace function

In [31]:
e=np.linspace(1,10,5)

In [32]:
e

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
a.min()

1.0

In [34]:
a.max()

5.0

In [36]:
a

array([1., 2., 3., 4., 5.])

In [37]:
a.sum()

15.0

In [38]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [39]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
a.sum(axis=0)

15.0

In [42]:
d.sum(axis=0)

array([12, 15, 18])

In [43]:
d.sum(axis=1)

array([ 6, 15, 24])

In [44]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [45]:
np.std(a)

1.4142135623730951

In [46]:
a

array([1., 2., 3., 4., 5.])

In [47]:
ss=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [48]:
sb=np.array([[11,12,13,14,15],[16,17,18,19,20]])

In [49]:
ss

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
sb

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
ss+sb

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [52]:
ss-sb

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [53]:
ss*sb

array([[ 11,  24,  39,  56,  75],
       [ 96, 119, 144, 171, 200]])

In [54]:
ss/sb

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
       [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]])

In [55]:
np.hstack([ss,sb])

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [56]:
np.vstack([ss,sb])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [57]:
b

array([[1, 2, 3],
       [4, 5, 6]])

#### Use of Ravel() and Flatten() Function

In [58]:
print(b.ravel())

[1 2 3 4 5 6]


In [59]:
print(b.flatten())

[1 2 3 4 5 6]


In [60]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [61]:
c.shape

(3, 3, 3)

In [62]:
a

array([1., 2., 3., 4., 5.])

#### Any and All Function

In [63]:
a.any()

True

In [64]:
a.all()

True

In [65]:
f=np.array([4,3,0,6,8])

In [66]:
f.any()

True

In [67]:
f.all()

False

In [68]:
g=np.array([0,0,0,0])

In [69]:
g.any()

False

In [70]:
g.all()

False

## Some Matrix Functions

In [71]:
a

array([1., 2., 3., 4., 5.])

In [72]:
a.fill(8)

In [73]:
a

array([8., 8., 8., 8., 8.])

In [74]:
np.full((3,2),1)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [75]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [76]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [77]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [79]:
h=np.zeros((3,3),int)

In [80]:
np.fill_diagonal(h,5)

In [81]:
h

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [82]:
np.full((2,2),2,complex)

array([[2.+0.j, 2.+0.j],
       [2.+0.j, 2.+0.j]])

In [83]:
x=np.array([[1,2],[3,4]])

In [84]:
np.dot(x,x)

array([[ 7, 10],
       [15, 22]])

### Use of Random Function

In [85]:
np.random.rand(5) 

array([0.36354818, 0.37360876, 0.13709564, 0.06823836, 0.69999055])

In [86]:
np.random.rand(5,5)

array([[0.5646999 , 0.21815958, 0.9998214 , 0.55600393, 0.1215263 ],
       [0.86650924, 0.47122097, 0.37292015, 0.0333172 , 0.50521658],
       [0.97363204, 0.88600976, 0.9555562 , 0.52644355, 0.94205764],
       [0.81963775, 0.79647105, 0.47808277, 0.47330805, 0.61151491],
       [0.66050922, 0.18254809, 0.61088896, 0.85836418, 0.65467441]])

In [87]:
np.random.randn(2)  #from std normal distribution around 0.

array([-0.4071946,  0.7317864])

In [88]:
np.random.randint(1,100)

61

In [89]:
np.random.randint(1,100,10)

array([16, 44, 41, 55, 43, 49, 89, 77, 40, 42])

In [90]:
ab=np.array([[1,2],[5,9]])

In [91]:
bc=np.array([[6,10],[8,11]])

In [92]:
cd=np.dot(ab,bc)

In [93]:
de=10*cd

In [94]:
de

array([[ 220,  320],
       [1020, 1490]])

# Pandas 

In [95]:
data=['a','b','c','d','e']

#### Making Dataframes in pandas

In [96]:
df=pd.DataFrame(data)

In [97]:
df

0
0  a
1  b
2  c
3  d
4  e

In [169]:
'''import sys
sys.executable'''

'import sys\nsys.executable'

In [99]:
data=np.array(['a','b','c','d'])

#### Making Series in Pandas

In [100]:
sp=pd.Series(data,index=[1,2,3,4])

In [101]:
sp

1    a
2    b
3    c
4    d
dtype: object

In [102]:
data={'a':0,'b':1,'c':0,'d':4}

In [103]:
s=pd.Series(data,index=['b','c','d','a','e'],dtype=float)

In [104]:
s

b    1.0
c    0.0
d    4.0
a    0.0
e    NaN
dtype: float64

In [105]:
s=pd.Series(5,index=[0,1,2,3,4])

In [106]:
s

0    5
1    5
2    5
3    5
4    5
dtype: int64

In [107]:
s=pd.Series([1,2,3,4,5,6])

In [108]:
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [109]:
s[0]

1

In [110]:
s[4]

5

In [111]:
s[:]

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [112]:
s[:3]

0    1
1    2
2    3
dtype: int64

In [113]:
s[::2]

0    1
2    3
4    5
dtype: int64

In [114]:
df=pd.DataFrame()

In [115]:
df

Empty DataFrame
Columns: []
Index: []

In [116]:
df.shape

(0, 0)

In [117]:
df.ndim

2

In [118]:
df.size

0

In [119]:
data=[1,2,3,4,5,6]

In [120]:
df=pd.DataFrame(data)

In [121]:
df

0
0  1
1  2
2  3
3  4
4  5
5  6

In [122]:
data=[['alex',10],['bob',12],['clarkee',16]]

In [123]:
df=pd.DataFrame(data,columns=['name','age'])

In [124]:
df

name  age
0     alex   10
1      bob   12
2  clarkee   16

In [125]:
data={'one':pd.Series([1,2,3],index=['a','b','c'],dtype=int),'two':pd.Series([1,3,4,5],index=['a','b','c','d'],dtype=int)}

In [126]:
df=pd.DataFrame(data)

In [127]:
df

one  two
a  1.0    1
b  2.0    3
c  3.0    4
d  NaN    5

In [128]:
df.iloc[2]

one    3.0
two    4.0
Name: c, dtype: float64

In [129]:
s=pd.Series(np.random.randn(2))

In [130]:
s

0   -1.364031
1    0.196478
dtype: float64

In [131]:
s=np.random.randn(3)

In [132]:
s

array([ 1.34147289, -0.25168565,  0.1072381 ])

In [133]:
s=pd.Series(np.random.randn(2))

In [134]:
s

0   -0.364704
1    2.498026
dtype: float64

In [135]:
s.axes

[RangeIndex(start=0, stop=2, step=1)]

In [136]:
s.empty

False

In [137]:
s.ndim

1

In [138]:
s.size

2

In [139]:
s.values

array([-0.36470363,  2.49802579])

In [140]:
s=pd.Series(np.random.randn(4))

In [141]:
s

0    0.022025
1   -0.389298
2    1.052104
3   -0.555966
dtype: float64

In [142]:
s.head(2)

0    0.022025
1   -0.389298
dtype: float64

In [143]:
s.tail(2)

2    1.052104
3   -0.555966
dtype: float64

## Dealing with Null Values(NaN)

In [144]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=[0,1,2],columns=['a','b','c'])

In [145]:
df

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [146]:
z=df.replace(5,'NaN')

In [147]:
z

a    b  c
0  1    2  3
1  4  NaN  6
2  7    8  9

In [148]:
d = {'A':[1,2,np.nan],'B':[4,np.nan,np.nan],'C':[7,4,5]}

In [149]:
df = pd.DataFrame(d)

In [150]:
df

A    B  C
0  1.0  4.0  7
1  2.0  NaN  4
2  NaN  NaN  5

In [151]:
df.dropna(axis=1)

C
0  7
1  4
2  5

In [152]:
df.dropna(thresh = 2)

A    B  C
0  1.0  4.0  7
1  2.0  NaN  4

In [153]:
df.fillna(value ='Fill Value')

A           B  C
0           1           4  7
1           2  Fill Value  4
2  Fill Value  Fill Value  5

In [154]:
df['A']

0    1.0
1    2.0
2    NaN
Name: A, dtype: float64

In [155]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [156]:
df.describe()

A    B         C
count  2.000000  1.0  3.000000
mean   1.500000  4.0  5.333333
std    0.707107  NaN  1.527525
min    1.000000  4.0  4.000000
25%    1.250000  4.0  4.500000
50%    1.500000  4.0  5.000000
75%    1.750000  4.0  6.000000
max    2.000000  4.0  7.000000

In [157]:
df.describe().transpose()

count      mean       std  min   25%  50%   75%  max
A    2.0  1.500000  0.707107  1.0  1.25  1.5  1.75  2.0
B    1.0  4.000000       NaN  4.0  4.00  4.0  4.00  4.0
C    3.0  5.333333  1.527525  4.0  4.50  5.0  6.00  7.0

In [158]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [159]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [160]:
df.sort_values('C')

A    B  C
1  2.0  NaN  4
2  NaN  NaN  5
0  1.0  4.0  7

In [161]:
df.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [162]:
# pd.read_csv('example.csv')

 pd.value_counts()  # used to count unique values

In [163]:
series1 = pd.Series([5,6.0,'Suyash',np.nan,'Mango'])

In [164]:
series1

0         5
1         6
2    Suyash
3       NaN
4     Mango
dtype: object

In [165]:
series1.isnull()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [166]:
series1.notnull()

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [167]:
series1.isnull().sum()

1

In [168]:
series1.notnull().sum()

4